package com.entity;

public class PacteraUser {

    private Integer userid;
    private String userlogin;
    private String password;
    private String telephone;

    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_user.platform_group_code
     *
     * @mbggenerated
     */
    private String platformGroupCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_user.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_user.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_user.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_user.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_user.vaild
     *
     * @mbggenerated
     */
    private String vaild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_user.field1
     *
     * @mbggenerated
     */
    private String field1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_user.field2
     *
     * @mbggenerated
     */
    private String field2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_user.field3
     *
     * @mbggenerated
     */
    private String field3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_user.field4
     *
     * @mbggenerated
     */
    private String field4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_user.field5
     *
     * @mbggenerated
     */
    private String field5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.userid
     *
     * @return the value of pactera_user.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.userid
     *
     * @param userid the value for pactera_user.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.userlogin
     *
     * @return the value of pactera_user.userlogin
     *
     * @mbggenerated
     */
    public String getUserlogin() {
        return userlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.userlogin
     *
     * @param userlogin the value for pactera_user.userlogin
     *
     * @mbggenerated
     */
    public void setUserlogin(String userlogin) {
        this.userlogin = userlogin == null ? null : userlogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.password
     *
     * @return the value of pactera_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.password
     *
     * @param password the value for pactera_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.telephone
     *
     * @return the value of pactera_user.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.telephone
     *
     * @param telephone the value for pactera_user.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.email
     *
     * @return the value of pactera_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.email
     *
     * @param email the value for pactera_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.platform_group_code
     *
     * @return the value of pactera_user.platform_group_code
     *
     * @mbggenerated
     */
    public String getPlatformGroupCode() {
        return platformGroupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.platform_group_code
     *
     * @param platformGroupCode the value for pactera_user.platform_group_code
     *
     * @mbggenerated
     */
    public void setPlatformGroupCode(String platformGroupCode) {
        this.platformGroupCode = platformGroupCode == null ? null : platformGroupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.username
     *
     * @return the value of pactera_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.username
     *
     * @param username the value for pactera_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.creator
     *
     * @return the value of pactera_user.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.creator
     *
     * @param creator the value for pactera_user.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.create_time
     *
     * @return the value of pactera_user.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.create_time
     *
     * @param createTime the value for pactera_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.update_time
     *
     * @return the value of pactera_user.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.update_time
     *
     * @param updateTime the value for pactera_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.modifier
     *
     * @return the value of pactera_user.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.modifier
     *
     * @param modifier the value for pactera_user.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.vaild
     *
     * @return the value of pactera_user.vaild
     *
     * @mbggenerated
     */
    public String getVaild() {
        return vaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.vaild
     *
     * @param vaild the value for pactera_user.vaild
     *
     * @mbggenerated
     */
    public void setVaild(String vaild) {
        this.vaild = vaild == null ? null : vaild.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.field1
     *
     * @return the value of pactera_user.field1
     *
     * @mbggenerated
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.field1
     *
     * @param field1 the value for pactera_user.field1
     *
     * @mbggenerated
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.field2
     *
     * @return the value of pactera_user.field2
     *
     * @mbggenerated
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.field2
     *
     * @param field2 the value for pactera_user.field2
     *
     * @mbggenerated
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.field3
     *
     * @return the value of pactera_user.field3
     *
     * @mbggenerated
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.field3
     *
     * @param field3 the value for pactera_user.field3
     *
     * @mbggenerated
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.field4
     *
     * @return the value of pactera_user.field4
     *
     * @mbggenerated
     */
    public String getField4() {
        return field4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.field4
     *
     * @param field4 the value for pactera_user.field4
     *
     * @mbggenerated
     */
    public void setField4(String field4) {
        this.field4 = field4 == null ? null : field4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_user.field5
     *
     * @return the value of pactera_user.field5
     *
     * @mbggenerated
     */
    public String getField5() {
        return field5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_user.field5
     *
     * @param field5 the value for pactera_user.field5
     *
     * @mbggenerated
     */
    public void setField5(String field5) {
        this.field5 = field5 == null ? null : field5.trim();
    }
}