package com.entity;

public class PacteraDemand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.demand_date
     *
     * @mbggenerated
     */
    private String demandDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.push_count
     *
     * @mbggenerated
     */
    private String pushCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.admitted_number
     *
     * @mbggenerated
     */
    private String admittedNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.wait_number
     *
     * @mbggenerated
     */
    private String waitNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.demand_gap
     *
     * @mbggenerated
     */
    private String demandGap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.agent_phone
     *
     * @mbggenerated
     */
    private String agentPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.demand_number
     *
     * @mbggenerated
     */
    private String demandNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.agent
     *
     * @mbggenerated
     */
    private String agent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.manager_phone
     *
     * @mbggenerated
     */
    private String managerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.manager
     *
     * @mbggenerated
     */
    private String manager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.skill_code
     *
     * @mbggenerated
     */
    private String skillCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.vaild
     *
     * @mbggenerated
     */
    private String vaild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.field1
     *
     * @mbggenerated
     */
    private String field1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.field2
     *
     * @mbggenerated
     */
    private String field2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.field3
     *
     * @mbggenerated
     */
    private String field3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.field4
     *
     * @mbggenerated
     */
    private String field4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pactera_demand.field5
     *
     * @mbggenerated
     */
    private String field5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.id
     *
     * @return the value of pactera_demand.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.id
     *
     * @param id the value for pactera_demand.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.demand_date
     *
     * @return the value of pactera_demand.demand_date
     *
     * @mbggenerated
     */
    public String getDemandDate() {
        return demandDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.demand_date
     *
     * @param demandDate the value for pactera_demand.demand_date
     *
     * @mbggenerated
     */
    public void setDemandDate(String demandDate) {
        this.demandDate = demandDate == null ? null : demandDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.modifier
     *
     * @return the value of pactera_demand.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.modifier
     *
     * @param modifier the value for pactera_demand.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.update_time
     *
     * @return the value of pactera_demand.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.update_time
     *
     * @param updateTime the value for pactera_demand.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.create_time
     *
     * @return the value of pactera_demand.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.create_time
     *
     * @param createTime the value for pactera_demand.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.push_count
     *
     * @return the value of pactera_demand.push_count
     *
     * @mbggenerated
     */
    public String getPushCount() {
        return pushCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.push_count
     *
     * @param pushCount the value for pactera_demand.push_count
     *
     * @mbggenerated
     */
    public void setPushCount(String pushCount) {
        this.pushCount = pushCount == null ? null : pushCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.admitted_number
     *
     * @return the value of pactera_demand.admitted_number
     *
     * @mbggenerated
     */
    public String getAdmittedNumber() {
        return admittedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.admitted_number
     *
     * @param admittedNumber the value for pactera_demand.admitted_number
     *
     * @mbggenerated
     */
    public void setAdmittedNumber(String admittedNumber) {
        this.admittedNumber = admittedNumber == null ? null : admittedNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.wait_number
     *
     * @return the value of pactera_demand.wait_number
     *
     * @mbggenerated
     */
    public String getWaitNumber() {
        return waitNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.wait_number
     *
     * @param waitNumber the value for pactera_demand.wait_number
     *
     * @mbggenerated
     */
    public void setWaitNumber(String waitNumber) {
        this.waitNumber = waitNumber == null ? null : waitNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.demand_gap
     *
     * @return the value of pactera_demand.demand_gap
     *
     * @mbggenerated
     */
    public String getDemandGap() {
        return demandGap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.demand_gap
     *
     * @param demandGap the value for pactera_demand.demand_gap
     *
     * @mbggenerated
     */
    public void setDemandGap(String demandGap) {
        this.demandGap = demandGap == null ? null : demandGap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.agent_phone
     *
     * @return the value of pactera_demand.agent_phone
     *
     * @mbggenerated
     */
    public String getAgentPhone() {
        return agentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.agent_phone
     *
     * @param agentPhone the value for pactera_demand.agent_phone
     *
     * @mbggenerated
     */
    public void setAgentPhone(String agentPhone) {
        this.agentPhone = agentPhone == null ? null : agentPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.creator
     *
     * @return the value of pactera_demand.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.creator
     *
     * @param creator the value for pactera_demand.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.demand_number
     *
     * @return the value of pactera_demand.demand_number
     *
     * @mbggenerated
     */
    public String getDemandNumber() {
        return demandNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.demand_number
     *
     * @param demandNumber the value for pactera_demand.demand_number
     *
     * @mbggenerated
     */
    public void setDemandNumber(String demandNumber) {
        this.demandNumber = demandNumber == null ? null : demandNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.agent
     *
     * @return the value of pactera_demand.agent
     *
     * @mbggenerated
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.agent
     *
     * @param agent the value for pactera_demand.agent
     *
     * @mbggenerated
     */
    public void setAgent(String agent) {
        this.agent = agent == null ? null : agent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.manager_phone
     *
     * @return the value of pactera_demand.manager_phone
     *
     * @mbggenerated
     */
    public String getManagerPhone() {
        return managerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.manager_phone
     *
     * @param managerPhone the value for pactera_demand.manager_phone
     *
     * @mbggenerated
     */
    public void setManagerPhone(String managerPhone) {
        this.managerPhone = managerPhone == null ? null : managerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.manager
     *
     * @return the value of pactera_demand.manager
     *
     * @mbggenerated
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.manager
     *
     * @param manager the value for pactera_demand.manager
     *
     * @mbggenerated
     */
    public void setManager(String manager) {
        this.manager = manager == null ? null : manager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.level
     *
     * @return the value of pactera_demand.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.level
     *
     * @param level the value for pactera_demand.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.skill_code
     *
     * @return the value of pactera_demand.skill_code
     *
     * @mbggenerated
     */
    public String getSkillCode() {
        return skillCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.skill_code
     *
     * @param skillCode the value for pactera_demand.skill_code
     *
     * @mbggenerated
     */
    public void setSkillCode(String skillCode) {
        this.skillCode = skillCode == null ? null : skillCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.state
     *
     * @return the value of pactera_demand.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.state
     *
     * @param state the value for pactera_demand.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.vaild
     *
     * @return the value of pactera_demand.vaild
     *
     * @mbggenerated
     */
    public String getVaild() {
        return vaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.vaild
     *
     * @param vaild the value for pactera_demand.vaild
     *
     * @mbggenerated
     */
    public void setVaild(String vaild) {
        this.vaild = vaild == null ? null : vaild.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.field1
     *
     * @return the value of pactera_demand.field1
     *
     * @mbggenerated
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.field1
     *
     * @param field1 the value for pactera_demand.field1
     *
     * @mbggenerated
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.field2
     *
     * @return the value of pactera_demand.field2
     *
     * @mbggenerated
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.field2
     *
     * @param field2 the value for pactera_demand.field2
     *
     * @mbggenerated
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.field3
     *
     * @return the value of pactera_demand.field3
     *
     * @mbggenerated
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.field3
     *
     * @param field3 the value for pactera_demand.field3
     *
     * @mbggenerated
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.field4
     *
     * @return the value of pactera_demand.field4
     *
     * @mbggenerated
     */
    public String getField4() {
        return field4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.field4
     *
     * @param field4 the value for pactera_demand.field4
     *
     * @mbggenerated
     */
    public void setField4(String field4) {
        this.field4 = field4 == null ? null : field4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pactera_demand.field5
     *
     * @return the value of pactera_demand.field5
     *
     * @mbggenerated
     */
    public String getField5() {
        return field5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pactera_demand.field5
     *
     * @param field5 the value for pactera_demand.field5
     *
     * @mbggenerated
     */
    public void setField5(String field5) {
        this.field5 = field5 == null ? null : field5.trim();
    }
}