package com.dao;

import com.entity.PacteraPlatformGroup;

public interface PacteraPlatformGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pactera_platform_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pactera_platform_group
     *
     * @mbggenerated
     */
    int insert(PacteraPlatformGroup pacteraPlatformGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pactera_platform_group
     *
     * @mbggenerated
     */
    int insertSelective(PacteraPlatformGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pactera_platform_group
     *
     * @mbggenerated
     */
    PacteraPlatformGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pactera_platform_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PacteraPlatformGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pactera_platform_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PacteraPlatformGroup record);
}